### ISSUE TITLE
Add to mister-devel repo

### ISSUE THREAD

**Issue by thehughhefner** [agg23/fpga-tamagotchi#3]
### Ask a question

Hi Agg,
Thank you for the core and good job!
I wonder if it would be possible for you to add this core to the mister-devel repo so that it can be fetched by downloader for mister? https://github.com/MiSTer-devel

Maybe it is better to create a separate repo that is part of the mister-devel? 
The developers of this discord can help you out: https://discord.gg/misterfpga

**Comment by agg23** [comment]
I will not be adding this repo to the `MiSTer-devel` org. Someone can fork it and add it if they wish, but I will not endorse that course of action. In any case, I don't think the MiSTer org would accept a repo with code for multiple supported platforms.

MiSTer `update_all` should be more robust for more repo configurations. For what I could tell from my brief looking at it, there is no centralized repository/API of core sources (because it assumes cores are located in the `MiSTer-devel` org, though a few devs have escaped that), and requires that binaries be committed to the repository, which is terrible practice. I certainly would like to provide users the better experience of easy and automatic installation, but unless someone gives me a good reason to, I tend to be pretty uncompromising with best practices. I don't expect anyone to make changes to accommodate me, given that this is a small core of minimal interest, but I'm happy to assist if they are so inclined.

I know the Discord server exists, and would like to utilize the dev resources there, but I have been the target of frequent harassment on that server by a few people. Stuff like that doesn't typically bother me, but I would just rather not expose myself to it, so I will do without.

**Comment by thehughhefner** [comment]
> In any case, I don't think the MiSTer org would accept a repo with code for multiple supported platforms.
> 
There are developers that have developed both for MiSTer and Pocket that has their code in the MiSTer org, although they have a separate repository for the respective platform. (See pram0d and nullobject cores). 

>MiSTer update_all should be more robust for more repo configurations. For what I could tell from my brief looking at it, there is no centralized repository/API of core sources (because it assumes cores are located in the MiSTer-devel org, though a few devs have escaped that), and requires that binaries be committed to the repository, which is terrible practice. I certainly would like to provide users the better experience of easy and automatic installation, but unless someone gives me a good reason to, I tend to be pretty uncompromising with best practices. I don't expect anyone to make changes to accommodate me, given that this is a small core of minimal interest, but I'm happy to assist if they are so inclined.
>

This is outside of my knowledge so I think it is better for Theypsilon or other core developers for MiSTer to respond to this

>I know the Discord server exists, and would like to utilize the dev resources there, but I have been the target of frequent harassment on that server by a few people. Stuff like that doesn't typically bother me, but I would just rather not expose myself to it, so I will do without.
> 

I'm sorry to hear that, but from what I've seen from that server is very helpful for developers.

**Comment by agg23** [comment]
I'm talking to theypsilon about the updater now.

**Comment by SegaSnatcher** [comment]
> > I know the Discord server exists, and would like to utilize the dev resources there, but I have been the target of frequent harassment on that server by a few people. Stuff like that doesn't typically bother me, but I would just rather not expose myself to it, so I will do without.
> 
> I'm sorry to hear that, but from what I've seen from that server is very helpful for developers. If it is just one person or two then they do not represent the community, regardless of "high status" they assume they have. At the end of the day, it is Sorg that is the maintainer of the devel repo

When the insults are coming straight from the Admins of that server I don't blame any dev who has been targeted by said individuals for not wanting to participate there. It is a shame that so many people seem to overlook such behavior from the community leaders.

Anyways, I'm just happy for agg23 and hope some individuals enjoy and appreciate this fun little core.

**Comment by birdybro** [comment]
Update all isn't officially part of mister-devel, it's a meta script that runs multiple other scripts, one of which is the mister update script, downloader. Downloader can reference a db which downloads whatever you want which could be used for distribution of this core.

**Comment by M-Walrus** [comment]
> > > I know the Discord server exists, and would like to utilize the dev resources there, but I have been the target of frequent harassment on that server by a few people. Stuff like that doesn't typically bother me, but I would just rather not expose myself to it, so I will do without.
> > 
> > 
> > I'm sorry to hear that, but from what I've seen from that server is very helpful for developers. If it is just one person or two then they do not represent the community, regardless of "high status" they assume they have. At the end of the day, it is Sorg that is the maintainer of the devel repo
> 
> When the insults are coming straight from the Admins of that server I don't blame any dev who has been targeted by said individuals for not wanting to participate there. It is a shame that so many people seem to overlook such behavior from the community leaders.
> 
> Anyways, I'm just happy for agg23 and hope some individuals enjoy and appreciate this fun little core.

For context in SegaSnatcher's personal view of this, he has been banned from every Discord I've shared with him for harassing other users and projects, to the point that he created his own Discord in order to slander the "terrible mods and admins" who "wronged him".  Also banned from many prominent YouTube channels like RetroRGB for similar behavior, and continues to spread misinformation about admins out of spite for the results of his own actions in all of these instances.  The wolf in sheep's clothes act he has persisted with continues to this day, unfortunately, but his record in all of these places still remains and bans will be upheld due to repeated behavior.  Every time he says he will do better when confronted about this, has turned out to be a falsehood and folks got fed up with it.  It's unfortunate this will have to be said every time he pops up to continue the same cycle.

**Comment by agg23** [comment]
I'm sorry I didn't respond when Sega originally posted. Please refrain from personal attacks and demeaning others. I will leave these comments up, but will be deleting any further ones.

**Comment by SegaSnatcher** [comment]
>  

agg23 has allowed me to defend myself, so I will do this while remaining as respectful as possible. 

First of all, I got banned from CGD because Rysha does not like anyone who offers criticism towards the MiSTer project and she took issue that I called out her and Sent's behavior towards myself and other users, so she asked Kevin to ban me, I didn't actually break any of the server's rules.  

Rysha and Sent prebanned me from the MiSTer server because of their grudge towards me, so CGD is technically only one server I was actually in with you that I was banned form. 

Also, RetroRGB has since unblocked me from twitter and I even follow him. I've had zero issues with him for at least 3 yrs now. 

I created my server because many people in the community wanted an alternative from the same moderation team that plagues both the MiSTer and CGD servers.  Don't act like I'm the only person who takes issue with those community leaders/mods behavior. There are many people who also see how problematic their behavior can be.   

We are almost 1600 members strong in my server and I think anyone who has been part of the server for awhile will say that its a really good community with very minimal issues regarding how people behave. I have yet to get PM'd from users complaining about bad moderation behavior.  Can the same be said of CGD or MiSTer servers?

Lastly, I ask you to provide whatever evidence you can find of behavior I engaged in that deserved me getting banned from CGD.  Because whatever you find I can match and more with bad behavior from the people you work under.  

You never saw me call anyone "Glory Parasites", but look at how your admins treat devs who work on Pocket.  What's the worst I said about someone?  That Sorg is "Stubborn"?   That Sent and Rysha are "petty"?  They have said way worse and yet I'm the toxic one?   

That is all I'll say on the matter.  I am a reasonable person who went out of my way many times to try and squash the beef  with the people in question, but they hold petty grudges and that is not my fault.

**Comment by thehughhefner** [comment]
I don’t want any drama here so I will remove comments from now on to respect agg23 wishes. No need to out moderators

**Comment by thehughhefner** [comment]
I don’t want any drama here and only asked for the core to be added to mister-devel. And agg23 has responded why, agree or disagree. The beauty of open source is that anyone can fork this, similar to who agg23 did by porting cores to Pocket. I will close this ticket

**Comment by agg23** [comment]
I'm sorry I let those comments stay up. I was hoping things could remain mostly civilized.

GitHub issues are not the place for controversial, non-technical discussions. Please do not use this platform to engage in such actions. Regardless of what you think of someone, everyone is to be treated with respect and compassion in a professional manner.
